//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServiceProgress", CallbackContract=typeof(ClientApp.ServiceReference.IServiceProgressCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServiceProgress {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProgress/DoProcess", ReplyAction="http://tempuri.org/IServiceProgress/DoProcessResponse")]
        int DoProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProgress/DoProcess", ReplyAction="http://tempuri.org/IServiceProgress/DoProcessResponse")]
        System.Threading.Tasks.Task<int> DoProcessAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProgressCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProgress/DeliverProgress", ReplyAction="http://tempuri.org/IServiceProgress/DeliverProgressResponse")]
        bool DeliverProgress(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProgressChannel : ClientApp.ServiceReference.IServiceProgress, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProgressClient : System.ServiceModel.DuplexClientBase<ClientApp.ServiceReference.IServiceProgress>, ClientApp.ServiceReference.IServiceProgress {
        
        public ServiceProgressClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceProgressClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceProgressClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProgressClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProgressClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int DoProcess() {
            return base.Channel.DoProcess();
        }
        
        public System.Threading.Tasks.Task<int> DoProcessAsync() {
            return base.Channel.DoProcessAsync();
        }
    }
}
